-- ============================================
-- Sample FAQs for University Community
-- Description: Common questions asked in university WhatsApp groups
-- Note: Embeddings will be generated by the application
-- ============================================

-- Clear existing data (use with caution in production!)
-- DELETE FROM faqs;

-- ============================================
-- CATEGORÍA: Matrícul

a
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Cuándo son las inscripciones para el próximo semestre?',
  'Las inscripciones para el semestre 2025-1 serán del 1 al 15 de marzo de 2025. Puedes realizarlas a través del portal estudiantil en https://portal.universidad.edu. Recuerda tener al día tus pagos y cumplir con los requisitos académicos.',
  'matricula',
  ARRAY['inscripciones', 'matricula', 'semestre', 'fechas'],
  '{"priority": "high", "last_updated": "2025-01-01", "source": "registro_academico"}'::jsonb
),
(
  '¿Cuáles son los requisitos para matricularse?',
  'Para matricularte necesitas: 1) Estar al día con tus pagos, 2) No tener sanciones disciplinarias, 3) Haber aprobado el semestre anterior (si no eres de primer ingreso), 4) Tener documentación completa (cédula, certificado de bachillerato), 5) Estar dentro de las fechas establecidas.',
  'matricula',
  ARRAY['requisitos', 'matricula', 'documentos'],
  '{"priority": "high", "last_updated": "2025-01-01"}'::jsonb
),
(
  '¿Puedo matricular menos de X créditos?',
  'Sí, puedes matricular entre 12 y 20 créditos por semestre. Si deseas matricular menos de 12 créditos, necesitas una autorización especial del director de carrera. Para más de 20 créditos, debes tener un promedio mínimo de 4.0 y solicitar aprobación.',
  'matricula',
  ARRAY['creditos', 'matricula', 'carga academica'],
  '{"priority": "medium"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Horarios
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Dónde puedo ver los horarios de las materias?',
  'Los horarios están disponibles en el portal estudiantil en la sección "Oferta Académica". También puedes consultarlos en https://horarios.universidad.edu. Los horarios se publican 2 semanas antes del inicio de cada semestre.',
  'horarios',
  ARRAY['horarios', 'materias', 'clases', 'oferta'],
  '{"priority": "high", "url": "https://horarios.universidad.edu"}'::jsonb
),
(
  '¿Puedo cambiar mi horario después de matricular?',
  'Sí, puedes hacer cambios en tu horario durante la primera semana de clases (período de ajustes). Después de esta fecha, solo se permiten cambios por causas de fuerza mayor y con aprobación del director de carrera.',
  'horarios',
  ARRAY['cambio', 'horario', 'ajustes'],
  '{"priority": "medium"}'::jsonb
),
(
  '¿Hay clases los sábados?',
  'Depende de tu programa académico. Algunos programas de posgrado y algunos cursos específicos tienen clases los sábados. Consulta tu horario específico en el portal estudiantil.',
  'horarios',
  ARRAY['sabado', 'clases', 'fin de semana'],
  '{"priority": "low"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Pagos y Finanzas
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Cuánto cuesta el semestre?',
  'El costo del semestre varía según tu programa y el número de créditos. En promedio, cada crédito cuesta $150.000 pesos. Un semestre de 16 créditos costaría aproximadamente $2.400.000. Consulta tu liquidación específica en el portal de pagos.',
  'pagos',
  ARRAY['costo', 'precio', 'semestre', 'matricula financiera'],
  '{"priority": "high", "requires_update": "yearly"}'::jsonb
),
(
  '¿Cómo puedo pagar la matrícula?',
  'Puedes pagar a través de: 1) PSE desde el portal estudiantil, 2) Transferencia bancaria a la cuenta 123-456789 Banco Nacional, 3) En efectivo en la tesorería de la universidad (solo de lunes a viernes 8am-4pm). Recuerda guardar el comprobante.',
  'pagos',
  ARRAY['pago', 'matricula', 'como pagar', 'metodos'],
  '{"priority": "high", "bank_account": "123-456789"}'::jsonb
),
(
  '¿Hay becas disponibles?',
  'Sí, ofrecemos varios tipos de becas: 1) Beca por mérito académico (promedio >4.5), 2) Beca socioeconómica (según estudio), 3) Beca deportiva, 4) Beca cultural. Las solicitudes se abren en enero y julio. Más info en bienestar@universidad.edu',
  'pagos',
  ARRAY['becas', 'ayuda economica', 'financiacion'],
  '{"priority": "high", "email": "bienestar@universidad.edu", "seasons": ["enero", "julio"]}'::jsonb
);

-- ============================================
-- CATEGORÍA: Biblioteca y Recursos
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Cuál es el horario de la biblioteca?',
  'La biblioteca está abierta de lunes a viernes de 7:00 AM a 9:00 PM, y sábados de 8:00 AM a 5:00 PM. Durante época de exámenes (últimas 2 semanas del semestre), extendemos el horario hasta las 11:00 PM entre semana.',
  'biblioteca',
  ARRAY['biblioteca', 'horario', 'horarios'],
  '{"priority": "medium", "extended_hours_during": "examenes"}'::jsonb
),
(
  '¿Cómo puedo sacar libros prestados?',
  'Para préstamo de libros necesitas: 1) Carnet estudiantil activo, 2) Estar al día con devoluciones anteriores, 3) Registrarte en el sistema de biblioteca. Puedes llevar hasta 3 libros por 15 días. Los préstamos se renuevan una vez si nadie más los ha reservado.',
  'biblioteca',
  ARRAY['prestamo', 'libros', 'biblioteca'],
  '{"priority": "medium", "max_books": 3, "loan_period_days": 15}'::jsonb
),
(
  '¿Hay salas de estudio?',
  'Sí, contamos con 10 salas de estudio grupal y 20 cubículos individuales. Puedes reservarlos en https://biblioteca.universidad.edu/salas con máximo 3 días de anticipación. Las reservas son por máximo 3 horas y debes llegar en los primeros 15 minutos o perderás la reserva.',
  'biblioteca',
  ARRAY['salas', 'estudio', 'reserva', 'cubiculos'],
  '{"priority": "medium", "url": "https://biblioteca.universidad.edu/salas"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Trámites y Documentos
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Cómo saco un certificado de estudios?',
  'Puedes solicitar certificados de estudios en el portal estudiantil > Trámites > Certificados. El certificado digital es gratuito y se envía a tu correo en 24 horas. El certificado físico tiene un costo de $15.000 y demora 3 días hábiles. Recógelo en la ventanilla 3 del edificio administrativo.',
  'tramites',
  ARRAY['certificado', 'estudios', 'documentos'],
  '{"priority": "high", "cost_physical": 15000, "delivery_time": "3 dias"}'::jsonb
),
(
  '¿Cómo actualizo mis datos personales?',
  'Puedes actualizar tus datos (teléfono, email, dirección) en el portal estudiantil > Mi Perfil. Para cambios en nombre o documento de identidad, debes presentarte en registro académico con los documentos oficiales que respalden el cambio.',
  'tramites',
  ARRAY['datos', 'actualizacion', 'perfil', 'informacion personal'],
  '{"priority": "medium"}'::jsonb
),
(
  '¿Cómo solicito mi carnet estudiantil?',
  'El carnet se solicita durante la primera semana de cada semestre en la oficina de carnets (edificio administrativo, segundo piso). Necesitas: foto fondo blanco 3x4, fotocopia de la cédula y comprobante de matrícula. El carnet se entrega en 5 días hábiles y tiene un costo de $10.000 (primera vez gratuita).',
  'tramites',
  ARRAY['carnet', 'identificacion', 'tarjeta'],
  '{"priority": "medium", "cost": 10000, "location": "edificio_admin_2piso"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Campus y Servicios
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Dónde está el edificio de X?',
  'Puedes ver el mapa interactivo del campus en https://mapa.universidad.edu. También hay mapas físicos en las entradas principales. Si necesitas direcciones específicas, pregunta en la portería o descarga la app móvil de la universidad que incluye navegación por el campus.',
  'campus',
  ARRAY['edificio', 'ubicacion', 'mapa', 'donde'],
  '{"priority": "medium", "url": "https://mapa.universidad.edu"}'::jsonb
),
(
  '¿Hay parqueadero para estudiantes?',
  'Sí, contamos con parqueadero para estudiantes en el sótano 1 y 2. El costo es $3.000 por día o puedes comprar una mensualidad de $60.000. La entrada es por la calle 45 con carrera 20. Llega temprano porque se llena rápido (capacidad para 200 vehículos).',
  'campus',
  ARRAY['parqueadero', 'estacionamiento', 'parqueo', 'vehiculos'],
  '{"priority": "medium", "daily_cost": 3000, "monthly_cost": 60000, "capacity": 200}'::jsonb
),
(
  '¿Hay WiFi en todo el campus?',
  'Sí, toda la universidad tiene cobertura WiFi. La red se llama "Universidad-Estudiantes". Para conectarte usa tu usuario del portal (tu código estudiantil) y tu contraseña. Si tienes problemas de conexión, reporta al email soporte@universidad.edu o visita sistemas en el edificio de tecnología.',
  'campus',
  ARRAY['wifi', 'internet', 'conexion', 'red'],
  '{"priority": "high", "network_name": "Universidad-Estudiantes", "support_email": "soporte@universidad.edu"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Bienestar y Salud
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Hay servicio médico en la universidad?',
  'Sí, el servicio de salud está en el edificio de bienestar, primer piso. Atención de lunes a viernes de 8 AM a 5 PM. Ofrecemos consulta médica general, psicología, odontología y primeros auxilios. El servicio es gratuito para estudiantes activos. Pide tu cita en salud@universidad.edu',
  'bienestar',
  ARRAY['salud', 'medico', 'enfermeria', 'doctor'],
  '{"priority": "high", "schedule": "lunes-viernes 8am-5pm", "email": "salud@universidad.edu"}'::jsonb
),
(
  '¿Hay gimnasio?',
  'Sí, tenemos gimnasio completamente equipado. Abierto de 6 AM a 9 PM todos los días. El acceso es gratuito para estudiantes. Debes registrarte en el primer uso y llevar tu carnet. También ofrecemos clases de yoga, spinning y crossfit. Horarios en deportes@universidad.edu',
  'bienestar',
  ARRAY['gimnasio', 'deportes', 'ejercicio', 'gym'],
  '{"priority": "medium", "schedule": "6am-9pm", "email": "deportes@universidad.edu"}'::jsonb
),
(
  '¿Hay cafetería en el campus?',
  'Sí, tenemos 3 cafeterías: 1) Cafetería Central (edificio principal), 2) Cafetería de Ingenierías, 3) Café del Jardín. Todas abiertas de 7 AM a 7 PM. Aceptamos efectivo, tarjeta y la app de la universidad. Menú del día desde $8.000. Menús en https://cafeteria.universidad.edu',
  'bienestar',
  ARRAY['cafeteria', 'comida', 'almuerzo', 'restaurante'],
  '{"priority": "medium", "url": "https://cafeteria.universidad.edu", "min_price": 8000}'::jsonb
);

-- ============================================
-- CATEGORÍA: Soporte Técnico
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  'No puedo entrar al portal estudiantil, ¿qué hago?',
  'Si no puedes acceder al portal: 1) Verifica que estás usando tu código estudiantil (no tu número de documento), 2) Intenta recuperar tu contraseña en "¿Olvidaste tu contraseña?", 3) Limpia caché y cookies del navegador, 4) Intenta desde otro navegador. Si el problema persiste, escribe a soporte@universidad.edu con tu código y una captura del error.',
  'soporte',
  ARRAY['portal', 'acceso', 'login', 'contraseña', 'no puedo entrar'],
  '{"priority": "high", "support_email": "soporte@universidad.edu"}'::jsonb
),
(
  '¿Cómo recupero mi contraseña?',
  'Para recuperar tu contraseña: 1) Ve a portal.universidad.edu, 2) Click en "¿Olvidaste tu contraseña?", 3) Ingresa tu código estudiantil, 4) Recibirás un código de verificación en tu email institucional, 5) Sigue las instrucciones para crear nueva contraseña. Si no recibes el email, verifica tu carpeta de spam.',
  'soporte',
  ARRAY['contraseña', 'recuperar', 'olvidé', 'reset'],
  '{"priority": "high"}'::jsonb
);

-- ============================================
-- CATEGORÍA: Contactos Importantes
-- ============================================
INSERT INTO faqs (question, answer, category, keywords, metadata) VALUES
(
  '¿Cuáles son los números de contacto principales?',
  'Contactos principales:\n• Información General: (+57) 601 234 5678\n• Admisiones: admisiones@universidad.edu\n• Registro Académico: registro@universidad.edu\n• Bienestar: bienestar@universidad.edu\n• Soporte Técnico: soporte@universidad.edu\n• Emergencias Campus: 123\n• WhatsApp Oficial: +57 310 123 4567',
  'contactos',
  ARRAY['contacto', 'telefono', 'email', 'correo', 'emergencia'],
  '{"priority": "high", "phone": "+57 601 234 5678", "whatsapp": "+57 310 123 4567"}'::jsonb
),
(
  '¿Dónde puedo hacer reclamos o sugerencias?',
  'Puedes hacer reclamos o sugerencias: 1) A través del buzón de sugerencias en el portal estudiantil, 2) Email a atencion@universidad.edu, 3) Presencialmente en la oficina de atención al estudiante (edificio administrativo, primer piso). Te responderemos en máximo 5 días hábiles.',
  'contactos',
  ARRAY['reclamos', 'sugerencias', 'quejas', 'pqrs'],
  '{"priority": "medium", "response_time": "5 dias", "email": "atencion@universidad.edu"}'::jsonb
);

-- ============================================
-- Summary: 25 FAQs across 9 categories
-- Categories: matricula, horarios, pagos, biblioteca, tramites, campus, bienestar, soporte, contactos
-- ============================================

-- Verify insertion
SELECT 
  category,
  COUNT(*) as faq_count
FROM faqs
GROUP BY category
ORDER BY faq_count DESC;

